version: '3.9'

services:

  db:
    container_name: postgres_container_for_asyncio
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"